#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
[[mods]] #mandatory
modId = "tfch" #mandatory
version = "1.20.0.1" #mandatory
displayName = "TFC Husbandry" #mandatory
authors = "Indi" #optional
description = '''Expands on all things animal husbandry for TerraFirmaCraft.'''

# Dependencies
[[dependencies.tfch]]
modId = "tfc"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfch]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfch]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "AFTER"
side = "BOTH"